name: Build

on: 
  push:
    branches:
      - master
    tags:
      - "*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
    - name: npm install
      run: npm i
      env:
       GITHUB_TOKEN: ${{ secrets.BLUPRINT_GITHUB_TOKEN }}
    - name: build
      run: |
        npm i
        npm i vsce -g
        node ./build/prepare-version.js
        node ./build/prepare.js
        npx vsce package -o skynet-blueprint-luadebug.vsix
    - name: Upload
      uses: actions/upload-artifact@v2
      with: 
        name: skynet-blueprint-luadebug
        path: ${{ github.workspace }}/skynet-blueprint-luadebug.vsix
  
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
      - run: npx vsce publish --packagePath $(find skynet-blueprint-luadebug -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_ACCESS_TOKEN }}